### ISSUE TITLE
Explain the implementation

### ISSUE THREAD

**Issue by itaditya** [aayush1408/Time-saver#1]

**Comment by aayush1408** [comment]
Mentioned the url of the social websites in the manifest.In the background script, button clicked event is handled, and a random motivational quote is send to the content script which listens for the event and then alerts out  the quote after fifteen minutes.

**Comment by itaditya** [comment]
how are you monitoring the time spent by the user on a site ?

**Comment by aayush1408** [comment]
when the user clicks the button, then the timer starts, its like the user can set the timer for himself.
